apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: www-asciidoc
  name: www-asciidoc
  namespace: ocp-directory
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: www-asciidoc
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www-asciidoc
        deploymentconfig: www-asciidoc
    spec:
      containers:
      - image: centos/httpd-24-centos7
        imagePullPolicy: Always
        name: www-asciidoc
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: www-data
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - clone
        - --single-branch
        - --
        - https://github.com/lbamford/ocp-asciidoc.git
        - /data
        image: alpine/git
        imagePullPolicy: Always
        name: git-cloner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: www-data
      - command:
        - bash
        - -c
        - sleep 2; asciidoctor *.adoc;
        image: asciidoctor/docker-asciidoctor
        imagePullPolicy: Always
        name: init-asciidoctor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /documents
          name: www-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: www-data
  test: false
